name-template: 'v2.$RESOLVED_VERSION 🌈'
tag-template: 'v2.$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR'
filter-by-commitish: true
commitish: v2
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'minor-release'
  minor:
    labels:
      - 'patch-release'
  default: minor
template: |
  ## Changes (v2 branch)

  $CHANGES
